name: NX CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  NX_BRANCH: ${{ github.head_ref }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - uses: bahmutov/npm-install@v1.6.0
        with:
          install-command: yarn --frozen-lockfile --prefer-offline --silent --no-progress
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --maxParallel=3
